language: python

python:
- '2.7'

env:
  global:
    - secure: M7HJl8DNMKDp1OURap4Qfxsbgz0zyOt1tT7KKAjkGQgiQP/QlynVeE3h9Ek5N8EIsS8hFoycqKKKfAL3xw4PBACEwVAMIuAap+l4SFAZxkxBrrTpx65UwbOSh1MpzkhAko4bM/dyrDbdNl2Lnz5vEpOLXHXGu8PFSNVVqauV9l0=

before_install:
  - git config --global user.email "jaeyoung@monodiary.net"
  - git config --global user.name "Travis"

install:
  - pip install -r requirements.txt

script:
  - git clone --depth 5 --quiet https://${GH_TOKEN}@github.com/Software-Maestro/__theme.git theme
  - git clone --depth 5 --quiet https://${GH_TOKEN}@github.com/Software-Maestro/Members.git member
  - git clone --depth 5 --quiet https://${GH_TOKEN}@github.com/Software-Maestro/software-maestro.github.io.git output
  - python generator.py
  - cp -r theme/static/* output/static/
  - cp -r theme/images/* output/images/

after_success:
  - cd output
  - git add -f .
  - git commit -a -m "Renew site contents"
  - git push https://${GH_TOKEN}@github.com/Software-Maestro/software-maestro.github.io.git master --quiet

branches:
  only:
    - master
